image: ubuntu2204

install:
  - sudo apt-get update
  - sudo apt-get install -y python3.11 python3.11-distutils python3.11-venv
  - wget https://bootstrap.pypa.io/get-pip.py
  - python3.11 get-pip.py

  - python3.11 -m venv venv
  - source venv/bin/activate

  - pip install --upgrade pip

  - chmod +x ./flaskapp/st.sh
  - pip install -r ./flaskapp/requirements.txt

test_script:
  - cd flaskapp
  - source ../venv/bin/activate
  - ./st.sh