image: ubuntu2204

install:
  # Установка Python 3.11 и зависимостей
  - sudo apt-get update
  - sudo apt-get install -y python3.11 python3.11-distutils python3.11-venv
  - wget https://bootstrap.pypa.io/get-pip.py
  - python3.11 get-pip.py

  # Создание виртуального окружения
  - python3.11 -m venv venv
  - source venv/bin/activate

  # Обновление pip и установка зависимостей
  - pip install --upgrade pip
  - chmod +x ./flaskapp/st.sh
  - pip install -r flaskapp/requirements.txt

  # Установка Node.js (для Vercel CLI)
  - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
  - sudo apt-get install -y nodejs

  # Установка Vercel CLI
  - npm install -g vercel

test_script:
  # Запуск тестов
  - cd flaskapp
  - source ../venv/bin/activate
  - ./st.sh

deploy_script:
  # Логин в Vercel с использованием токена API
  - vercel login --token Wk0rCZqv4z1ojyxQfaRnBdwE

  # Деплой приложения на Vercel
  - cd ..
  - vercel --prod --token Wk0rCZqv4z1ojyxQfaRnBdwE